# Generated by Django 5.2.6 on 2025-11-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_alter_contact_address_alter_contact_city_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='myapp1_cont_email_4c898c_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['tel_number'], name='myapp1_cont_tel_num_2fc357_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['city'], name='myapp1_cont_city_e3d83e_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['specialty'], name='myapp1_cont_special_861852_idx'),
        ),
    ]
